/* Alternative symbols from mdi */
#define LV_SYMBOL_BULLET          "\xf3\xb0\xa7\x9f" /* mdi-circle-small */
#define LV_SYMBOL_AUDIO           "\xf3\xb0\x9d\x9a" /* mdi-music */
#define LV_SYMBOL_VIDEO           "\xf3\xb0\x8e\x81" /* mdi-movie */
#define LV_SYMBOL_LIST            "\xf3\xb0\x95\xb2" /* mdi-list */
#define LV_SYMBOL_OK              "\xf3\xb0\x84\xac" /* mdi-check */
#define LV_SYMBOL_CLOSE           "\xf3\xb0\x85\x96" /* mdi-close */
#define LV_SYMBOL_POWER           "\xf3\xb0\x90\xa5" /* mdi-power */
#define LV_SYMBOL_SETTINGS        "\xf3\xb0\x92\x93" /* mdi-cog */
#define LV_SYMBOL_HOME            "\xf3\xb0\x8b\x9c" /* mdi-home */
#define LV_SYMBOL_DOWNLOAD        "\xf3\xb0\x87\x9a" /* mdi-download */
#define LV_SYMBOL_DRIVE           "\xf3\xb0\x9a\x87" /* mdi-inbox */
#define LV_SYMBOL_REFRESH         "\xf3\xb0\x91\x90" /* mdi-refresh */
#define LV_SYMBOL_MUTE            "\xf3\xb0\x95\xbf" /* mdi-volume-low */
#define LV_SYMBOL_VOLUME_MID      "\xf3\xb0\x96\x80" /* mdi-volume-medium */
#define LV_SYMBOL_VOLUME_MAX      "\xf3\xb0\x95\xbe" /* mdi-volume-high */
#define LV_SYMBOL_IMAGE           "\xf3\xb0\x8b\xa9" /* mdi-image */
#define LV_SYMBOL_TINT            "\xf3\xb0\x96\x8c" /* mdi-water */
#define LV_SYMBOL_PREV            "\xf3\xb0\x92\xae" /* mdi-skip-previous */
#define LV_SYMBOL_PLAY            "\xf3\xb0\x90\x8a" /* mdi-play */
#define LV_SYMBOL_PAUSE           "\xf3\xb0\x8f\xa4" /* mdi-pause */
#define LV_SYMBOL_STOP            "\xf3\xb0\x93\x9b" /* mdi-stop */
#define LV_SYMBOL_NEXT            "\xf3\xb0\x92\xad" /* mdi-skip-next */
#define LV_SYMBOL_EJECT           "\xf3\xb0\x87\xaa" /* mdi-eject */
#define LV_SYMBOL_LEFT            "\xf3\xb0\x85\x81" /* mdi-chevron-left */
#define LV_SYMBOL_RIGHT           "\xf3\xb0\x85\x82" /* mdi-chevron-right */
#define LV_SYMBOL_PLUS            "\xf3\xb0\x90\x95" /* mdi-plus */
#define LV_SYMBOL_MINUS           "\xf3\xb0\x8d\xb4" /* mdi-minus */
#define LV_SYMBOL_EYE_OPEN        "\xf3\xb0\x88\x88" /* mdi-eye */
#define LV_SYMBOL_EYE_CLOSE       "\xf3\xb0\x88\x89" /* mdi-eye-off */
#define LV_SYMBOL_WARNING         "\xf3\xb0\x80\xa6" /* mdi-alert */
#define LV_SYMBOL_SHUFFLE         "\xf3\xb0\x92\x9f" /* mdi-shuffle-variant */
#define LV_SYMBOL_UP              "\xf3\xb0\x85\x83" /* mdi-chevron-up */
#define LV_SYMBOL_DOWN            "\xf3\xb0\x85\x80" /* mdi-chevron-down */
#define LV_SYMBOL_LOOP            "\xf3\xb0\x93\xa6" /* mdi-sync */
#define LV_SYMBOL_DIRECTORY       "\xf3\xb0\x89\x8b" /* mdi-folder */
#define LV_SYMBOL_UPLOAD          "\xf3\xb0\x95\x92" /* mdi-upload */
#define LV_SYMBOL_CALL            "\xf3\xb0\x8f\xb2" /* mdi-phone */
#define LV_SYMBOL_CUT             "\xf3\xb0\x86\x90" /* mdi-content-cut */
#define LV_SYMBOL_COPY            "\xf3\xb0\x86\x8f" /* mdi-content-copy */
#define LV_SYMBOL_SAVE            "\xf3\xb0\x86\x93" /* mdi-content-save */
#define LV_SYMBOL_BARS            "\xf3\xb0\x8d\x9c" /* mdi-menu */
#define LV_SYMBOL_ENVELOPE        "\xf3\xb0\x87\xae" /* mdi-email */
#define LV_SYMBOL_CHARGE          "\xf3\xb0\x89\x81" /* mdi-flash */
#define LV_SYMBOL_PASTE           "\xf3\xb0\x86\x92" /* mdi-content-paste */
#define LV_SYMBOL_BELL            "\xf3\xb0\x82\x9a" /* mdi-bell */
#define LV_SYMBOL_KEYBOARD        "\xf3\xb0\x8c\x8c" /* mdi-keyboard */
#define LV_SYMBOL_GPS             "\xf3\xb1\xa3\xb0" /* mdi-navigation-variant */
#define LV_SYMBOL_FILE            "\xf3\xb0\x88\x94" /* mdi-file */
#define LV_SYMBOL_WIFI            "\xf3\xb0\x96\xa9" /* mdi-wifi */
#define LV_SYMBOL_BATTERY_FULL    "\xf3\xb0\x81\xb9" /* mdi-battery */
#define LV_SYMBOL_BATTERY_3       "\xf3\xb0\x82\x81" /* mdi-battery-80 */
#define LV_SYMBOL_BATTERY_2       "\xf3\xb0\x81\xbe" /* mdi-battery-50 */
#define LV_SYMBOL_BATTERY_1       "\xf3\xb0\x81\xbb" /* mdi-battery-20 */
#define LV_SYMBOL_BATTERY_EMPTY   "\xf3\xb0\x82\x8e" /* mdi-battery-outline */
#define LV_SYMBOL_USB             "\xf3\xb0\x95\x93" /* mdi-usb */
#define LV_SYMBOL_BLUETOOTH       "\xf3\xb0\x82\xaf" /* mdi-bluetooth */
#define LV_SYMBOL_TRASH           "\xf3\xb0\xa9\xb9" /* mdi-trash-can */
#define LV_SYMBOL_EDIT            "\xf3\xb0\x8f\xab" /* mdi-pencil */
#define LV_SYMBOL_BACKSPACE       "\xf3\xb0\x81\xae" /* mdi-backspace */
#define LV_SYMBOL_SD_CARD         "\xf3\xb0\x91\xb9" /* mdi-sd */
#define LV_SYMBOL_NEW_LINE        "\xf3\xb0\x8c\x91" /* mdi-keyboard-return */
#define LV_SYMBOL_DUMMY           "\xf3\xb0\x85\x98" /* mdi-close-box-outline */
