#define ASM
#include"builtin.h"
BUILTIN_FILE(file_svg_cdrom,"../assets/cdrom.svg")
BUILTIN_FILE(file_svg_default,"../assets/default.svg")
BUILTIN_FILE(file_svg_disk,"../assets/disk.svg")
BUILTIN_FILE(file_svg_flash,"../assets/flash.svg")
BUILTIN_FILE(file_svg_floppy,"../assets/floppy.svg")
BUILTIN_FILE(file_svg_mmc,"../assets/mmc.svg")
BUILTIN_FILE(file_svg_usb,"../assets/usb.svg")

.section .note.GNU-stack,""
